spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
        - id: order-route
          uri: ${ORDER_ROUTE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**
